# Copyright (C) 2024 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

# cargo-vet audits file

[[audits.enum-kinds]]
who = "Casper Meijn <casper@meijn.net>"
criteria = "safe-to-deploy"
version = "0.5.1"

[[audits.mock_instant]]
who = "Casper Meijn <casper@meijn.net>"
criteria = "safe-to-deploy"
version = "0.3.2"
