
# cargo-vet audits file

[[audits.enum-kinds]]
who = "Casper Meijn <casper@meijn.net>"
criteria = "safe-to-deploy"
version = "0.5.1"

[[audits.mock_instant]]
who = "Casper Meijn <casper@meijn.net>"
criteria = "safe-to-deploy"
version = "0.3.2"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-03-29"
